### ISSUE TITLE
Minetweaker support for IE 0.7 is invalid

### ISSUE THREAD

**Issue by LYDfalse** [stanhebben/MineTweaker3#301] opened 2016-01-15 06:30 UTC
Run Minecraft tips Error executing XXX.zs:null

**Comment by jaredlll08** [comment] 2016-01-15 06:33
First of all, this is the wrong repo, IE adds support natively.
Second: you provided NO information, none of what you provided is useful, I
suggest getting more info, such as your scripts, the minetweaker.log file
and what isn't working.

**Comment by LYDfalse** [comment] 2016-01-15 06:46
https://gist.github.com/LYDfalse/8abbad3b4898a0903a52
https://gist.github.com/LYDfalse/3f0bd600ff2f15bb5849

**Comment by jaredlll08** [comment] 2016-01-15 06:49
Ok! We are getting there, however, you are still missing the fact that
thinsis the MINETWEAKER repo, not the Immersive Engineering repo, so you
can give me all the info in the world, but I can't do anything about ut.

**Comment by LYDfalse** [comment] 2016-01-15 10:47
This is to open the world of information
https://gist.github.com/LYDfalse/cd8cb7d19379040a4725

**Comment by PrincessRTFM** [comment] 2016-01-15 11:41
He can't help you. It's not his code that's broken. This is the wrong repo to report to. Stop reporting here, because it won't make a difference.

**Comment by LYDfalse** [comment] 2016-01-15 11:55
Well, only wait for updates

**Comment by jaredlll08** [comment] 2016-01-15 14:51
@LYDfalse Please tell me what your primary language is, so I can translate sow you can understand

**Comment by copygirl** [comment] 2016-01-15 16:39
@jaredlll08 I understand this may not necessarily be something you'd want to do for each reported bug, but why not report this to IE's tracker yourself, with the information provided so far?

**Comment by jaredlll08** [comment] 2016-01-15 16:43
Few reasons, 
If I do that, users don't learn.
They will ask for information that I don't have
There is hardly any information for IE to help them fix it

**Comment by LYDfalse** [comment] 2016-01-16 03:03
@jaredlll08 My primary language is Chinese

**Comment by Blue64** [comment] 2016-01-17 02:16
@LYDfalse:
问题是，有身临其境的工程基本代码

MineTweaker√

[沉浸工程](https://github.com/BluSunrize/ImmersiveEngineering)×

报告沉浸工程国防部请。

(Basically, I [translated](http://translate.google.com) to Chinese Simplified to report to Immersive Engineering Mod)

**Comment by jaredlll08** [comment] 2016-01-17 09:19
Thanks @Blue64

**Comment by BluSunrize** [comment] 2016-01-17 14:31
You know what would be really helpful? Actually telling the IE dev >____<

You can't just go "I'll wait for a fix" if it was never reported. Luckily I found it myself and fixed it for 0.7.1.

Whoever manages this can close it, the issue is resolved.

**Closed** 2016-01-17 15:39 UTC
